In [1]:
import pandas as pd
print(pd.__version__)

3.0.2

In [2]:
obj = pd.Series([4, 7, -5, 3])
print(obj)
obj.values
obj.index

0    4
1    7
2   -5
3    3
dtype: int64

RangeIndex(start=0, stop=4, step=1)

In [3]:
import numpy as np


obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2.sort_index()
obj2.values
obj2.index
print(obj2)
obj2['a']
print(int(obj2['a']))
obj2[['c', 'a', 'd']] # ['c', 'a', 'd']是索引列表，即使它包含的是字符串而不是整数。
obj2[obj2 > 0]
obj2 * 2 # type: ignore
np.exp(obj2)  # noqa: F821

'b' in obj2

d    4
b    7
a   -5
c    3
dtype: int64
-5

True

In [4]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
print(obj3)
obj3['Ohio']

states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
print(f'\n{obj4}')

pd.isnull(obj4) # 判断是否为空
pd.notnull(obj4)
obj4.isnull()

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [5]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)

states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [6]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

obj4.name = 'population'
obj4.index.name = 'state'

obj4.index = ['Bob', 'Steve', 'Jeff', 'Ryan'] # 重新设置索引,索引名会重置
obj4.index.name = 'name'
print(obj4)

obj4.index = pd.Index(['California', 'Ohio', 'Oregon', 'Texas'], name='states')
print(obj4)

name
Bob          NaN
Steve    35000.0
Jeff     16000.0
Ryan     71000.0
Name: population, dtype: float64
states
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [7]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
print(frame)

frame.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [8]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [9]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
index=['one', 'two', 'three', 'four', 'five', 'six'])
print(frame2)

frame2.columns

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [10]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: str

In [11]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [12]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [13]:
frame2['debt'] = [1,2,3,4,5,6]
frame2

       year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     2
three  2002    Ohio  3.6     3
four   2001  Nevada  2.4     4
five   2002  Nevada  2.9     5
six    2003  Nevada  3.2     6

In [14]:
frame2['debt'] = np.arange(6.)
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [15]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [16]:
frame2['eastern'] = frame2.state == 'Ohio'
del frame2['eastern']

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='str')

In [17]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [18]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [19]:
pd.DataFrame(pop, index=[2001, 2002, 2003])
# 内层字典的键会被合并、排序以形成最终的索引。如果明确指定了索引，则不会这样

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [20]:
obj = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.0
b    7.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [21]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [22]:
frame = pd.DataFrame(np.arange(10).reshape(5, 2), index = ['a','b','c','d','e'],columns=['A', 'B'])
frame

   A  B
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9

In [23]:
frame2 = frame.reindex(['a', 'b', 'c', 'd','e','f'])
frame2

     A    B
a  0.0  1.0
b  2.0  3.0
c  4.0  5.0
d  6.0  7.0
e  8.0  9.0
f  NaN  NaN

In [24]:
states = ['A', 'B', 'C']
frame2.reindex(columns=states)

     A    B   C
a  0.0  1.0 NaN
b  2.0  3.0 NaN
c  4.0  5.0 NaN
d  6.0  7.0 NaN
e  8.0  9.0 NaN
f  NaN  NaN NaN

In [25]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj = obj.drop(['d', 'c'])
new_obj

a    0.0
b    1.0
e    4.0
dtype: float64

In [26]:
frame = pd.DataFrame(np.arange(16).reshape(4, 4), index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['A', 'B', 'C', 'D'])
new_frame = frame.drop('Ohio')
new_frame

           A   B   C   D
Colorado   4   5   6   7
Utah       8   9  10  11
New York  12  13  14  15

In [27]:
new_frame2 = frame.drop(['A','B'],axis = 'columns')
new_frame2

           C   D
Ohio       2   3
Colorado   6   7
Utah      10  11
New York  14  15

In [28]:
obj.drop('c', inplace=True) # inplace=True是改变原对象,小心使用inplace，它会销毁所有被删除的数据
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [29]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

print(obj['b'])          # 按标签
print(obj.iloc[1])       # 按位置
print(obj.iloc[2:4])     # 按位置切片
print(obj[['b', 'a', 'd']])  # 按标签列表
print(obj.iloc[[1, 3]])  # 按位置列表
print(obj[obj < 2])      # 布尔筛选
print(obj['b':'c'])      # 按标签切片，包含 c

obj['b':'c'] = 5
print(obj)

1.0
1.0
c    2.0
d    3.0
dtype: float64
b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64
a    0.0
b    1.0
dtype: float64
b    1.0
c    2.0
dtype: float64
a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [30]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.arange(12).reshape(3, 4),
    index=['a', 'b', 'c'],
    columns=['one', 'two', 'three', 'four']
)

print(df)

print(df['one'])
print(df[['one', 'three']])

print(df.loc['b']) 
# df.loc 是 pandas 里按标签索引的工具，也就是说，它不是按“第几行、第几列”取数据，而是按 行名 index 和 列名 columns 取数据
print(df.iloc[1])
print(df.loc[['a', 'c']])

print(df.loc['b', 'three'])
print(df.loc[['a', 'c'], ['one', 'four']])

print(df.iloc[1, 2])
print(df.iloc[[0, 2], [0, 3]])

print(df.loc['a':'b', 'two':'four'])
print(df.iloc[0:2, 1:4])

# df['列名']              # 取列
# df.loc['行标签']        # 按行标签取行
# df.iloc[行位置]          # 按行位置取行

# df.loc[行标签, 列标签]    # 按标签取某个值
# df.iloc[行位置, 列位置]  # 按位置取某个值

   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
a    0
b    4
c    8
Name: one, dtype: int64
   one  three
a    0      2
b    4      6
c    8     10
one      4
two      5
three    6
four     7
Name: b, dtype: int64
one      4
two      5
three    6
four     7
Name: b, dtype: int64
   one  two  three  four
a    0    1      2     3
c    8    9     10    11
6
   one  four
a    0     3
c    8    11
6
   one  four
a    0     3
c    8    11
   two  three  four
a    1      2     3
b    5      6     7
   two  three  four
a    1      2     3
b    5      6     7

In [31]:
dates = pd.date_range("20130101", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  1.271286  1.036565 -0.467998 -0.257656
2013-01-02  0.501673 -0.360087 -1.045647  1.615474
2013-01-03  0.273865  0.497039  1.212796  0.444552
2013-01-04  0.104627  1.139771 -0.552238 -0.359657
2013-01-05  0.832267  0.377886  0.019413 -1.006401
2013-01-06  0.719424 -1.443777 -0.732978  1.566173

In [32]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [33]:
df.head(2)

                   A         B         C         D
2013-01-01  1.271286  1.036565 -0.467998 -0.257656
2013-01-02  0.501673 -0.360087 -1.045647  1.615474

In [34]:
df.tail(2)

                   A         B         C         D
2013-01-05  0.832267  0.377886  0.019413 -1.006401
2013-01-06  0.719424 -1.443777 -0.732978  1.566173

In [35]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [36]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [37]:
df.to_numpy()

array([[ 1.27128554,  1.03656488, -0.46799844, -0.25765567],
       [ 0.50167329, -0.36008748, -1.04564733,  1.61547356],
       [ 0.27386523,  0.49703909,  1.2127956 ,  0.44455231],
       [ 0.10462682,  1.1397708 , -0.55223827, -0.35965653],
       [ 0.83226716,  0.3778861 ,  0.01941328, -1.0064005 ],
       [ 0.71942386, -1.44377734, -0.73297788,  1.56617311]])

In [38]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [39]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [40]:
df.describe() # 描述统计

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.617190  0.207899 -0.261109  0.333748
std    0.419163  0.971413  0.802098  1.077083
min    0.104627 -1.443777 -1.045647 -1.006401
25%    0.330817 -0.175594 -0.687793 -0.334156
50%    0.610549  0.437463 -0.510118  0.093448
75%    0.804056  0.901683 -0.102440  1.285768
max    1.271286  1.139771  1.212796  1.615474

In [41]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.271286    0.501673    0.273865    0.104627    0.832267    0.719424
B    1.036565   -0.360087    0.497039    1.139771    0.377886   -1.443777
C   -0.467998   -1.045647    1.212796   -0.552238    0.019413   -0.732978
D   -0.257656    1.615474    0.444552   -0.359657   -1.006401    1.566173

In [42]:
df.sort_index(axis=1, ascending=False) # ascending=False means descending

                   D         C         B         A
2013-01-01 -0.257656 -0.467998  1.036565  1.271286
2013-01-02  1.615474 -1.045647 -0.360087  0.501673
2013-01-03  0.444552  1.212796  0.497039  0.273865
2013-01-04 -0.359657 -0.552238  1.139771  0.104627
2013-01-05 -1.006401  0.019413  0.377886  0.832267
2013-01-06  1.566173 -0.732978 -1.443777  0.719424

In [43]:
df.sort_values(by="B")

                   A         B         C         D
2013-01-06  0.719424 -1.443777 -0.732978  1.566173
2013-01-02  0.501673 -0.360087 -1.045647  1.615474
2013-01-05  0.832267  0.377886  0.019413 -1.006401
2013-01-03  0.273865  0.497039  1.212796  0.444552
2013-01-01  1.271286  1.036565 -0.467998 -0.257656
2013-01-04  0.104627  1.139771 -0.552238 -0.359657

In [44]:
df["A"]

2013-01-01    1.271286
2013-01-02    0.501673
2013-01-03    0.273865
2013-01-04    0.104627
2013-01-05    0.832267
2013-01-06    0.719424
Freq: D, Name: A, dtype: float64

In [45]:
df.A

2013-01-01    1.271286
2013-01-02    0.501673
2013-01-03    0.273865
2013-01-04    0.104627
2013-01-05    0.832267
2013-01-06    0.719424
Freq: D, Name: A, dtype: float64

In [46]:
df[["B", "A"]]

                   B         A
2013-01-01  1.036565  1.271286
2013-01-02 -0.360087  0.501673
2013-01-03  0.497039  0.273865
2013-01-04  1.139771  0.104627
2013-01-05  0.377886  0.832267
2013-01-06 -1.443777  0.719424

In [47]:
df[0:3]

                   A         B         C         D
2013-01-01  1.271286  1.036565 -0.467998 -0.257656
2013-01-02  0.501673 -0.360087 -1.045647  1.615474
2013-01-03  0.273865  0.497039  1.212796  0.444552

In [48]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02  0.501673 -0.360087 -1.045647  1.615474
2013-01-03  0.273865  0.497039  1.212796  0.444552
2013-01-04  0.104627  1.139771 -0.552238 -0.359657

In [49]:
df

                   A         B         C         D
2013-01-01  1.271286  1.036565 -0.467998 -0.257656
2013-01-02  0.501673 -0.360087 -1.045647  1.615474
2013-01-03  0.273865  0.497039  1.212796  0.444552
2013-01-04  0.104627  1.139771 -0.552238 -0.359657
2013-01-05  0.832267  0.377886  0.019413 -1.006401
2013-01-06  0.719424 -1.443777 -0.732978  1.566173

In [50]:
df.loc[dates[0]]

A    1.271286
B    1.036565
C   -0.467998
D   -0.257656
Name: 2013-01-01 00:00:00, dtype: float64

In [ ]:
df.loc[:,['A','B']] # : all rows

                   A         B
2013-01-01  1.271286  1.036565
2013-01-02  0.501673 -0.360087
2013-01-03  0.273865  0.497039
2013-01-04  0.104627  1.139771
2013-01-05  0.832267  0.377886
2013-01-06  0.719424 -1.443777

In [53]:
df.loc["20130102":"20130104", ["A", "B"]]

                   A         B
2013-01-02  0.501673 -0.360087
2013-01-03  0.273865  0.497039
2013-01-04  0.104627  1.139771

In [54]:
df.loc[dates[0], "A"]

np.float64(1.2712855441141264)

In [55]:
df.at[dates[0], "A"]

np.float64(1.2712855441141264)

In [56]:
df.iloc[3]

A    0.104627
B    1.139771
C   -0.552238
D   -0.359657
Name: 2013-01-04 00:00:00, dtype: float64

In [57]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04  0.104627  1.139771
2013-01-05  0.832267  0.377886

In [58]:
df.iloc[[1, 2, 4], [0, 2]]

                   A         C
2013-01-02  0.501673 -1.045647
2013-01-03  0.273865  1.212796
2013-01-05  0.832267  0.019413

In [59]:
df.iloc[1:3, :]

                   A         B         C         D
2013-01-02  0.501673 -0.360087 -1.045647  1.615474
2013-01-03  0.273865  0.497039  1.212796  0.444552

In [60]:
df.iloc[:, 1:3]

                   B         C
2013-01-01  1.036565 -0.467998
2013-01-02 -0.360087 -1.045647
2013-01-03  0.497039  1.212796
2013-01-04  1.139771 -0.552238
2013-01-05  0.377886  0.019413
2013-01-06 -1.443777 -0.732978