In [1]:
import pandas as pd
pd.__version__

'3.0.2'

In [2]:
from pathlib import Path
path = Path.cwd()
path

WindowsPath('c:/Users/hp/Desktop/Python_Projects/my_project/09_pyda-2e_study')

In [3]:
df = pd.read_csv(path / 'output/foo.csv')
df

   Unnamed: 0  0  1  2  3  4
0           0  2  4  1  2  3
1           1  1  3  2  4  1
2           2  0  1  2  0  1
3           3  2  3  0  0  0
4           4  0  1  3  3  1
5           5  3  0  1  1  0
6           6  0  4  2  4  3
7           7  1  3  0  4  3
8           8  2  4  3  2  4
9           9  3  4  2  1  2

In [4]:
!type output\foo.csv

,0,1,2,3,4
0,2,4,1,2,3
1,1,3,2,4,1
2,0,1,2,0,1
3,2,3,0,0,0
4,0,1,3,3,1
5,3,0,1,1,0
6,0,4,2,4,3
7,1,3,0,4,3
8,2,4,3,2,4
9,3,4,2,1,2

In [5]:
pd.read_table(path / 'output/foo.csv', sep=',')

   Unnamed: 0  0  1  2  3  4
0           0  2  4  1  2  3
1           1  1  3  2  4  1
2           2  0  1  2  0  1
3           3  2  3  0  0  0
4           4  0  1  3  3  1
5           5  3  0  1  1  0
6           6  0  4  2  4  3
7           7  1  3  0  4  3
8           8  2  4  3  2  4
9           9  3  4  2  1  2

In [6]:
import pandas as pd
from pathlib import Path

# 创建 DataFrame
df = pd.DataFrame({
    'a': [1, 5, 9],
    'b': [2, 6, 10],
    'c': [3, 7, 11],
    'd': [4, 8, 12],
    'message': ['hello', 'world', 'foo']
})

df2 = pd.DataFrame([
    [1, 5, 9],
    [2, 6, 10],
    [3, 7, 11],
    [4, 8, 12],
    ['hello', 'world', 'foo']
    ]).T # 转置


# 定义保存路径
path = Path.cwd()

# 写入 CSV 文件
df.to_csv(path / 'data' / 'ex1.csv', index=False)
df2.to_csv(path / 'data' / 'ex2.csv', index=False, header=False) # index=False 不保存行索引, header=False 不保存列名


print("文件写入成功！")

文件写入成功！

In [7]:
pd.read_table(path / 'data/ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
df2 = pd.read_csv(path / 'data/ex2.csv', header=None) # 不包含表头
df2

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [9]:
df2 = pd.read_csv(path / 'data/ex2.csv',  names=['a', 'b', 'c', 'd', 'message'], index_col='message') 
df2

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [10]:
import pandas as pd
from pathlib import Path

# 定义路径
path = Path.cwd()

# 创建数据
data = [
    ['one', 'a', 1, 2],
    ['one', 'b', 3, 4],
    ['one', 'c', 5, 6],
    ['one', 'd', 7, 8],
    ['two', 'a', 9, 10],
    ['two', 'b', 11, 12],
    ['two', 'c', 13, 14],
    ['two', 'd', 15, 16]
]

# 创建 DataFrame
df = pd.DataFrame(data, columns=['key1', 'key2', 'value1', 'value2'])

# 保存为 CSV
df.to_csv(path / 'data/csv_mindex.csv', index=False)

print("文件创建成功！")
print(df)

文件创建成功！
  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [11]:
parsed = pd.read_csv(path / 'data/csv_mindex.csv', index_col=['key1', 'key2']) 
# 读取 CSV 文件，设置多级索引
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [12]:
list(open('examples/ex3.txt')) # 以列表形式读取文本文件

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [13]:
result = pd.read_table('examples/ex3.txt', sep='\\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [14]:
!type examples\ex4.csv
# 一定要用反斜杠，否则会报错

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [15]:
pd.read_csv('examples/ex4.csv', skiprows=[0, 2, 3])
# 读取 CSV 文件，跳过指定行 0、2、3

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [16]:
! type examples\ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [17]:
result = pd.read_csv('examples/ex5.csv')
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [18]:
result = pd.read_csv('examples/ex5.csv', na_values=['NULL'])
result
# 在读取数据文件时，你可以传入一个列表（list）或集合（set），里面包含多个字符串，pandas 会将这些字符串都识别为缺失值（NaN）

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [19]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
# 你也可以传入一个字典（dict），为不同的列指定不同的缺失值标记
pd.read_csv('examples/ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [20]:
result = pd.read_csv('examples/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [21]:
pd.read_csv('examples/ex6.csv', nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [22]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)
chunker

In [23]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)
# 迭代读取数据块，并对每个块进行处理

tot = pd.Series([])
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)
tot[:10]

key
E    368
X    364
L    346
O    343
Q    340
M    338
J    337
F    335
K    334
H    330
dtype: object

In [24]:
s = pd.Series({'a': 10, 'b': 20, 'c': 30})
# 键变成索引，值变成数据
s.iloc[0]
s.index[0]

'a'

In [25]:
import pandas as pd

s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s2 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

s1.add(s2)
# a    11
# b    22
# c    33

a    11
b    22
c    33
dtype: int64

In [26]:
s = pd.Series(['a', 'b', 'a', 'a', 'c', 'b', 'a'])

counts = s.value_counts()
print(counts)
# a    4    ← 'a' 出现 4 次
# b    2    ← 'b' 出现 2 次
# c    1    ← 'c' 出现 1 次
# dtype: int64

a    4
b    2
c    1
Name: count, dtype: int64

In [27]:
data = pd.read_csv('examples/ex5.csv')
data.to_csv('examples/out.csv')

In [28]:
import sys
data.to_csv(sys.stdout, sep='|')
# sys.stdout 是一个类文件对象，指向标准输出流（通常是控制台）。当你将 DataFrame 输出到 sys.stdout 时，它会以文本形式显示在控制台上，而不是写入文件。sep='|' 参数指定了字段之间的分隔符，这里使用竖线（|）代替默认的逗号（,）。

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [29]:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [30]:
data.to_csv(sys.stdout, index=False, header=False)
# index=False 不保存行索引, header=False 不保存列名

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [31]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [32]:
import numpy as np
dates = pd.date_range('1/1/2000', periods=7) # 创建一个日期范围，从 2000 年 1 月 1 日开始，包含 7 天
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('examples/tseries.csv')

In [33]:
import csv
f = open('examples/ex7.csv')

reader = csv.reader(f)
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [34]:
with open('examples/ex7.csv') as f:
    lines = list(csv.reader(f))

header, values = lines[0], lines[1:]
data_dict = {h: v for h, v in zip(header, zip(*values))} 
# zip(*values) 将 values 列表中的每个元素（行）解压成单独的列表，然后与 header 列表中的每个元素（列名）配对，创建一个字典，其中键是列名，值是对应列的  数据列表
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [35]:
import csv

# 1. 先在外面定义好你的“方言”规则
class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ','
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

# 2. 重新开门，并在这个门关上之前把读取的工作做完
with open('examples/ex7.csv') as f:
    # 让翻译官拿着新手册去读这个刚刚打开的文件 f
    reader = csv.reader(f, dialect=my_dialect)
    
    # 💥重要提示：你要对数据做的任何处理，都必须在这个缩进里完成！
    # 比如你想把数据打印出来看看：
    for line in reader:
        print(line)
        
# 一旦代码退出了上面的缩进跑到这里，文件 f 就又会自动关上了。

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [36]:
with open('examples/ex7.csv') as f:
    # 让翻译官拿着新手册去读这个刚刚打开的文件 f
    reader = csv.reader(f)

    for line in reader:
        print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [37]:
import json

obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

result = json.loads(obj)
asjson = json.dumps(result) # 将 Python 对象转换成 JSON 字符串
print(result)
print(asjson)

{'name': 'Wes', 'places_lived': ['United States', 'Spain', 'Germany'], 'pet': None, 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']}, {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}
{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}

In [38]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age', 'pets'])
siblings

    name  age                    pets
0  Scott   30            [Zeus, Zuko]
1  Katie   38  [Sixes, Stache, Cisco]

In [39]:
data = pd.read_json('examples/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [40]:
tables = pd.read_html('examples/fdic_failed_bank_list.html')
failures = tables[0]

In [41]:
close_timestamps = pd.to_datetime(failures['Closing Date'])
print(close_timestamps)
close_timestamps.dt.year.value_counts()
#     └─────┘ └────┘ └────────────┘
#        ↓      ↓          ↓
#    datetime  提取年份   统计各年份出现次数
#    Series   (int类型)   (返回Series)

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[us]

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, dtype: int64

In [42]:
# 按月份统计
print(f'{close_timestamps.dt.month.value_counts()}\n')

# 按季度统计
print(close_timestamps.dt.quarter.value_counts(), end='\n\n')

# 按星期几统计
print(close_timestamps.dt.dayofweek.value_counts())

# 组合：按年月统计
print(close_timestamps.dt.to_period('M').value_counts())

Closing Date
7     74
4     58
10    58
1     49
2     44
8     41
5     41
3     39
9     38
6     36
11    35
12    34
Name: count, dtype: int64

Closing Date
3    153
2    135
1    132
4    127
Name: count, dtype: int64

Closing Date
4    522
3     19
2      2
1      2
5      1
0      1
Name: count, dtype: int64
Closing Date
2009-07    24
2010-04    23
2010-07    22
2009-10    20
2010-03    19
           ..
2001-07     1
2001-05     1
2001-02     1
2000-12     1
2000-10     1
Freq: M, Name: count, Length: 108, dtype: int64

In [43]:
frame = pd.read_csv('examples/ex1.csv')
frame.to_pickle('examples/frame_pickle') # 将 DataFrame 保存为 pickle 文件
pd.read_pickle('examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [44]:
xlsx = pd.ExcelFile('examples/ex1.xlsx')
# 要使用ExcelFile，通过传递xls或xlsx路径创建一个实例
pd.read_excel(xlsx, 'Sheet1', index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [45]:
frame = pd.read_excel('examples/ex1.xlsx', 'Sheet1', index_col=0)
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [46]:
# 用 with 语句打开 Writer，在缩进里把数据写进去，结束时自动保存并关闭
with pd.ExcelWriter('examples/ex2.xlsx') as writer:
    frame.to_excel(writer, sheet_name='Sheet1', index=False)

# index=False 不保存行索引,避免保存行索引到 Excel 文件中，因为 Excel 文件通常不需要行索引，除非你有特殊需求。

In [47]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
data = resp.json()
# 服务器退回来的数据通常是一长串纯文本（格式叫做 JSON）。resp.json() 的作用是把这串干巴巴的纯文本，瞬间转换成 Python 里极其好用的数据结构（通常是“包含许多字典的大列表”）。现在，data 里面装的就是 Pandas 项目中最近被提及的一堆 Issue 数据。
data[0]
len(data)

30

In [48]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues['labels']

0                                                    []
1                                                    []
2                                                    []
3                                                    []
4                                                    []
5                                                    []
6     [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
7     [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...
8                                                    []
9     [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
10    [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...
11    [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
12    [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...
13    [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
14    [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...
15    [{'id': 1508144531, 'node_id': 'MDU6TGFiZWwxNT...
16                                                   []
17                                                   []
18                                                   []
19                                                   []
20                                                   []
21                                                   []
22                                                   []
23                                                   []
24    [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...
25    [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...
26                                                   []
27                                                   []
28    [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...
29                                                   []
Name: labels, dtype: object

In [49]:
import polars as pl
import datetime as dt

df = pl.DataFrame(
    {
        "name": ["Alice Archer", "Ben Brown", "Chloe Cooper", "Daniel Donovan"],
        "birthdate": [
            dt.date(1997, 1, 10),
            dt.date(1985, 2, 15),
            dt.date(1983, 3, 22),
            dt.date(1981, 4, 30),
        ],
        "weight": [57.9, 72.5, 53.6, 83.1],  # (kg)
        "height": [1.56, 1.77, 1.65, 1.75],  # (m)
    }
)

print(df)

shape: (4, 4)
┌────────────────┬────────────┬────────┬────────┐
│ name           ┆ birthdate  ┆ weight ┆ height │
│ ---            ┆ ---        ┆ ---    ┆ ---    │
│ str            ┆ date       ┆ f64    ┆ f64    │
╞════════════════╪════════════╪════════╪════════╡
│ Alice Archer   ┆ 1997-01-10 ┆ 57.9   ┆ 1.56   │
│ Ben Brown      ┆ 1985-02-15 ┆ 72.5   ┆ 1.77   │
│ Chloe Cooper   ┆ 1983-03-22 ┆ 53.6   ┆ 1.65   │
│ Daniel Donovan ┆ 1981-04-30 ┆ 83.1   ┆ 1.75   │
└────────────────┴────────────┴────────┴────────┘

In [50]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: str

In [51]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool