In [2]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

3.0.2
2.4.4

In [4]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data.isnull()
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [6]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna() # 删除所有包含缺失值的行
data[data.notnull()] # 只保留非缺失值

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data = pd.DataFrame(
    [
        [1., 6.5, 3.], 
        [1., np.nan, np.nan],
        [np.nan, np.nan, np.nan], 
        [np.nan, 6.5, 3.],
    ]
)
print(data)
cleaned = data.dropna()
cleaned

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

     0    1    2
0  1.0  6.5  3.0

In [9]:
cleaned = data.dropna(how='all') # 只删除全为NA的行
cleaned

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [13]:
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [14]:
data.dropna(axis=1, how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [ ]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df.dropna(thresh=2)
# thresh=2 的意思是保留至少包含 2 个非 NA 值的行。不够 2 个非 NA 值的行会被删除。

          0         1         2
2  0.398741       NaN  1.407516
3 -0.369747       NaN -0.819861
4 -0.145752 -0.408213 -0.250359
5  0.043337 -0.295582  1.620623
6 -0.622664 -0.071573 -0.457427

In [20]:
df.fillna(0)

          0         1         2
0  0.597701  0.000000  0.000000
1 -0.459756  0.000000  0.000000
2  0.398741  0.000000  1.407516
3 -0.369747  0.000000 -0.819861
4 -0.145752 -0.408213 -0.250359
5  0.043337 -0.295582  1.620623
6 -0.622664 -0.071573 -0.457427

In [ ]:
df.fillna({1: 0.5, 2: 0}) # 只替换第 1 列的 NA 值为 0.5，第 2 列的 NA 值为 0。

          0         1         2
0  0.597701  0.500000  0.000000
1 -0.459756  0.500000  0.000000
2  0.398741  0.500000  1.407516
3 -0.369747  0.500000 -0.819861
4 -0.145752 -0.408213 -0.250359
5  0.043337 -0.295582  1.620623
6 -0.622664 -0.071573 -0.457427

In [ ]:
_ = df.fillna(0, inplace=True) 
# _ 是为了不返回一个新的 DataFrame，而是直接在原 DataFrame 上进行修改。
# inplace=True 的意思是直接在原 DataFrame 上进行修改，而不是返回一个新的 DataFrame。
df

          0         1         2
0  0.597701  0.000000  0.000000
1 -0.459756  0.000000  0.000000
2  0.398741  0.000000  1.407516
3 -0.369747  0.000000 -0.819861
4 -0.145752 -0.408213 -0.250359
5  0.043337 -0.295582  1.620623
6 -0.622664 -0.071573 -0.457427

In [26]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df.ffill()  # 前向填充，将缺失值填充为前一个非缺失值。

          0         1         2
0  0.271038  1.832668  0.908393
1  0.162152  0.511140  2.022635
2  0.403678  0.511140  1.393885
3  0.424785  0.511140 -0.168418
4 -0.395021  0.511140 -0.168418
5  0.493322  0.511140 -0.168418

In [27]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [ ]:
data = pd.DataFrame(
    {
        'k1': ['one', 'two'] * 3 + ['two'],
        'k2': [1, 1, 2, 3, 3, 4, 4]
    }
)
data.duplicated() # 检查是否有重复行

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [30]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data['v1'] = range(7)
data.drop_duplicates(['k1'], keep='first')
# keep='first' 表示保留第一个重复行，删除后续重复行。

    k1  k2  v1
0  one   1   0
1  two   1   1

In [33]:
data.drop_duplicates(['k1', 'k2'], keep='last')
# keep='last' 表示保留最后一个重复行，删除其他重复行。

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [36]:
data = pd.DataFrame(
    {
        'food': ['bacon', 'pulled pork', 'bacon','Pastrami', 'corned beef', 'Bacon','pastrami', 'honey ham', 'nova lox'],
        'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]
    }
)

meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [ ]:
lowercased = data['food'].str.lower()
data['animal'] = lowercased.map(meat_to_animal)
# Series.map(dict) 会把 Series 中每个值当作 key 去字典里查，返回对应的 value
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [38]:
import pandas as pd
import numpy as np

s = pd.Series(['cat', 'dog', 'rabbit', 'dog', np.nan])
print(s)

# 中文翻译
cn = {'cat': '猫', 'dog': '狗', 'rabbit': '兔子'}
s.map(cn)

0       cat
1       dog
2    rabbit
3       dog
4       NaN
dtype: str

0      猫
1      狗
2     兔子
3      狗
4    NaN
dtype: str

In [ ]:
import pandas as pd

s = pd.Series(['cat', 'dog', 'rabbit', 'cat', 'dog'])
# 使用函数转换
result = s.map(lambda x: x.upper()) # 把每个元素转换为大写，lambda 函数是匿名函数，没有名字
print(result)
# 输出:
# 0       CAT
# 1       DOG
# 2    RABBIT
# 3       CAT
# 4       DOG
# dtype: object

0       CAT
1       DOG
2    RABBIT
3       CAT
4       DOG
dtype: str

In [44]:
s = pd.Series(['cat', 'dog', 'rabbit', 'cat', 'dog'])
# 使用字典进行映射
mapping = {'cat': '小猫', 'dog': '小狗', 'rabbit': '兔子'}
result = s.map(mapping)
print(result)
# 输出:
# 0    小猫
# 1    小狗
# 2    兔子
# 3    小猫
# 4    小狗
# dtype: object

0    小猫
1    小狗
2    兔子
3    小猫
4    小狗
dtype: str

In [45]:
s = pd.Series(['cat', 'dog', 'rabbit', 'cat', 'dog'])
mapping = {'cat': '小猫', 'dog': '小狗'}  # 没有 rabbit 的映射
result = s.map(mapping)
print(result)
# 输出:
# 0    小猫
# 1    小狗
# 2     NaN  # 找不到映射时变成 NaN
# 3    小猫
# 4    小狗
# dtype: object

0     小猫
1     小狗
2    NaN
3     小猫
4     小狗
dtype: str

In [ ]:
s = pd.Series(['cat', 'dog', None, 'cat'])
mapping = {'cat': '小猫', 'dog': '小狗'}

# 忽略 NaN 值
result = s.map(mapping, na_action='ignore') 
# na_action='ignore' 的意思是当遇到 NaN 值时，保持 NaN 不变，而不是尝试去映射它。
print(result)
# 输出:
# 0    小猫
# 1    小狗
# 2    None
# 3    小猫
# dtype: object

0     小猫
1     小狗
2    NaN
3     小猫
dtype: str

In [48]:
s = pd.Series([1, 2, 3, 1, 2])
mapping = {1: '低', 2: '中', 3: '高'}
result = s.map(mapping)
print(result)
# 输出:
# 0    低
# 1    中
# 2    高
# 3    低
# 4    中
# dtype: object

0    低
1    中
2    高
3    低
4    中
dtype: str

In [49]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'city': ['Beijing', 'Shanghai', 'Beijing'],
    'score': [85, 92, 78]
})

# 对单列使用 map
city_mapping = {'Beijing': '北京', 'Shanghai': '上海'}
df['city_cn'] = df['city'].map(city_mapping)
print(df)

      name      city  score city_cn
0    Alice   Beijing     85      北京
1      Bob  Shanghai     92      上海
2  Charlie   Beijing     78      北京

In [50]:
s = pd.Series(['a', 'b', 'c'])
mapping_series = pd.Series(['A', 'B', 'C'], index=['a', 'b', 'c'])
result = s.map(mapping_series)
print(result)
# 输出:
# 0    A
# 1    B
# 2    C
# dtype: object

0    A
1    B
2    C
dtype: str

In [51]:
df = pd.DataFrame({
    'gender': ['M', 'F', 'Male', 'Female', 'm', 'f']
})

# 统一性别格式
gender_mapping = {
    'M': 'Male', 'm': 'Male', 'Male': 'Male',
    'F': 'Female', 'f': 'Female', 'Female': 'Female'
}
df['gender_clean'] = df['gender'].map(gender_mapping)
print(df)

   gender gender_clean
0       M         Male
1       F       Female
2    Male         Male
3  Female       Female
4       m         Male
5       f       Female

In [53]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data = data.replace(-999, np.nan, inplace=True)
data
# 输出:
# 0    1.0
# 1    NaN
# 2    2.0
# 3    NaN
# 4    -1000.0
# 5    3.0
# dtype: float64

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [ ]:
data.replace([-999, -1000], np.nan, inplace=True)
# 这行代码的意思是把 data 中的 -999 和 -1000 都替换成 np.nan，inplace=True 表示直接在原 data 上修改，而不是返回一个新的 Series。

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [56]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
data = pd.DataFrame(
    np.arange(12).reshape((3, 4)),
    index=['Ohio', 'Colorado', 'New York'],
    columns=['one', 'two', 'three', 'four'],
    )
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [63]:
data.index = data.index.map(lambda x: x[:4].upper())
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [ ]:
data.rename(index=str.title, columns=str.upper)
# index=str.title：对索引（行名）应用 str.title() 函数（首字母大写）
# columns=str.upper：对列名应用 str.upper() 函数（全部大写）

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [66]:
import pandas as pd

data = pd.DataFrame({
    'name': ['Alice', 'Bob'],
    'age': [25, 30],
    'city': ['Beijing', 'Shanghai']
}, index=['row_one', 'row_two'])

print("原始数据:")
print(data)
# 输出:
#           name  age      city
# row_one  Alice   25   Beijing
# row_two    Bob   30  Shanghai

# 修改索引和列名
result = data.rename(index=str.title, columns=str.upper)
print("\n修改后:")
print(result)
# 输出:
#           NAME  AGE      CITY
# Row_One  Alice   25   Beijing
# Row_Two    Bob   30  Shanghai

原始数据:
          name  age      city
row_one  Alice   25   Beijing
row_two    Bob   30  Shanghai

修改后:
          NAME  AGE      CITY
Row_One  Alice   25   Beijing
Row_Two    Bob   30  Shanghai

In [67]:
# 假设从 Excel 读取的数据列名不规范
data = pd.DataFrame({
    '  Name ': ['Alice', 'Bob'],
    'AGE': [25, 30],
    'city ': ['Beijing', 'Shanghai']
}, index=['001', '002'])

# 清理列名：去空格 + 转小写
data.columns = data.columns.str.strip().str.lower()

# 或者用 rename
data = data.rename(columns=lambda x: x.strip().lower())

print(data)
# 输出:
#       name  age      city
# 001  Alice   25   Beijing
# 002    Bob   30  Shanghai

      name  age      city
001  Alice   25   Beijing
002    Bob   30  Shanghai