In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

3.0.2
2.4.4

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data.isnull()
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [3]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna() # 删除所有包含缺失值的行
data[data.notnull()] # 只保留非缺失值

0    1.0
2    3.5
4    7.0
dtype: float64

In [4]:
data = pd.DataFrame(
    [
        [1., 6.5, 3.], 
        [1., np.nan, np.nan],
        [np.nan, np.nan, np.nan], 
        [np.nan, 6.5, 3.],
    ]
)
print(data)
cleaned = data.dropna()
cleaned

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

     0    1    2
0  1.0  6.5  3.0

In [5]:
cleaned = data.dropna(how='all') # 只删除全为NA的行
cleaned

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [6]:
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [7]:
data.dropna(axis=1, how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df.dropna(thresh=2)
# thresh=2 的意思是保留至少包含 2 个非 NA 值的行。不够 2 个非 NA 值的行会被删除。

          0         1         2
2 -0.308990       NaN -0.775410
3  1.508628       NaN -0.814913
4  0.664757 -1.139027  0.658637
5  0.103487 -1.374847  0.551332
6  0.802718  2.364757 -0.274381

In [9]:
df.fillna(0)

          0         1         2
0 -0.008201  0.000000  0.000000
1 -0.861037  0.000000  0.000000
2 -0.308990  0.000000 -0.775410
3  1.508628  0.000000 -0.814913
4  0.664757 -1.139027  0.658637
5  0.103487 -1.374847  0.551332
6  0.802718  2.364757 -0.274381

In [10]:
df.fillna({1: 0.5, 2: 0}) # 只替换第 1 列的 NA 值为 0.5，第 2 列的 NA 值为 0。

          0         1         2
0 -0.008201  0.500000  0.000000
1 -0.861037  0.500000  0.000000
2 -0.308990  0.500000 -0.775410
3  1.508628  0.500000 -0.814913
4  0.664757 -1.139027  0.658637
5  0.103487 -1.374847  0.551332
6  0.802718  2.364757 -0.274381

In [11]:
_ = df.fillna(0, inplace=True) 
# _ 是为了不返回一个新的 DataFrame，而是直接在原 DataFrame 上进行修改。
# inplace=True 的意思是直接在原 DataFrame 上进行修改，而不是返回一个新的 DataFrame。
df

          0         1         2
0 -0.008201  0.000000  0.000000
1 -0.861037  0.000000  0.000000
2 -0.308990  0.000000 -0.775410
3  1.508628  0.000000 -0.814913
4  0.664757 -1.139027  0.658637
5  0.103487 -1.374847  0.551332
6  0.802718  2.364757 -0.274381

In [12]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df.ffill()  # 前向填充，将缺失值填充为前一个非缺失值。

          0         1         2
0  0.094947 -0.806472 -0.245072
1 -1.998253 -0.702472  1.092387
2 -0.599043 -0.702472  0.837461
3  0.454296 -0.702472 -0.117861
4  0.471556 -0.702472 -0.117861
5  1.054353 -0.702472 -0.117861

In [13]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [14]:
data = pd.DataFrame(
    {
        'k1': ['one', 'two'] * 3 + ['two'],
        'k2': [1, 1, 2, 3, 3, 4, 4]
    }
)
data.duplicated() # 检查是否有重复行

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [15]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [16]:
data['v1'] = range(7)
data.drop_duplicates(['k1'], keep='first')
# keep='first' 表示保留第一个重复行，删除后续重复行。

    k1  k2  v1
0  one   1   0
1  two   1   1

In [17]:
data.drop_duplicates(['k1', 'k2'], keep='last')
# keep='last' 表示保留最后一个重复行，删除其他重复行。

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [18]:
data = pd.DataFrame(
    {
        'food': ['bacon', 'pulled pork', 'bacon','Pastrami', 'corned beef', 'Bacon','pastrami', 'honey ham', 'nova lox'],
        'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]
    }
)

meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [19]:
lowercased = data['food'].str.lower()
data['animal'] = lowercased.map(meat_to_animal)
# Series.map(dict) 会把 Series 中每个值当作 key 去字典里查，返回对应的 value
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [20]:
import pandas as pd
import numpy as np

s = pd.Series(['cat', 'dog', 'rabbit', 'dog', np.nan])
print(s)

# 中文翻译
cn = {'cat': '猫', 'dog': '狗', 'rabbit': '兔子'}
s.map(cn)

0       cat
1       dog
2    rabbit
3       dog
4       NaN
dtype: str

0      猫
1      狗
2     兔子
3      狗
4    NaN
dtype: str

In [21]:
import pandas as pd

s = pd.Series(['cat', 'dog', 'rabbit', 'cat', 'dog'])
# 使用函数转换
result = s.map(lambda x: x.upper()) # 把每个元素转换为大写，lambda 函数是匿名函数，没有名字
print(result)
# 输出:
# 0       CAT
# 1       DOG
# 2    RABBIT
# 3       CAT
# 4       DOG
# dtype: object

0       CAT
1       DOG
2    RABBIT
3       CAT
4       DOG
dtype: str

In [22]:
s = pd.Series(['cat', 'dog', 'rabbit', 'cat', 'dog'])
# 使用字典进行映射
mapping = {'cat': '小猫', 'dog': '小狗', 'rabbit': '兔子'}
result = s.map(mapping)
print(result)
# 输出:
# 0    小猫
# 1    小狗
# 2    兔子
# 3    小猫
# 4    小狗
# dtype: object

0    小猫
1    小狗
2    兔子
3    小猫
4    小狗
dtype: str

In [23]:
s = pd.Series(['cat', 'dog', 'rabbit', 'cat', 'dog'])
mapping = {'cat': '小猫', 'dog': '小狗'}  # 没有 rabbit 的映射
result = s.map(mapping)
print(result)
# 输出:
# 0    小猫
# 1    小狗
# 2     NaN  # 找不到映射时变成 NaN
# 3    小猫
# 4    小狗
# dtype: object

0     小猫
1     小狗
2    NaN
3     小猫
4     小狗
dtype: str

In [24]:
s = pd.Series(['cat', 'dog', None, 'cat'])
mapping = {'cat': '小猫', 'dog': '小狗'}

# 忽略 NaN 值
result = s.map(mapping, na_action='ignore') 
# na_action='ignore' 的意思是当遇到 NaN 值时，保持 NaN 不变，而不是尝试去映射它。
print(result)
# 输出:
# 0    小猫
# 1    小狗
# 2    None
# 3    小猫
# dtype: object

0     小猫
1     小狗
2    NaN
3     小猫
dtype: str

In [25]:
s = pd.Series([1, 2, 3, 1, 2])
mapping = {1: '低', 2: '中', 3: '高'}
result = s.map(mapping)
print(result)
# 输出:
# 0    低
# 1    中
# 2    高
# 3    低
# 4    中
# dtype: object

0    低
1    中
2    高
3    低
4    中
dtype: str

In [26]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'city': ['Beijing', 'Shanghai', 'Beijing'],
    'score': [85, 92, 78]
})

# 对单列使用 map
city_mapping = {'Beijing': '北京', 'Shanghai': '上海'}
df['city_cn'] = df['city'].map(city_mapping)
print(df)

      name      city  score city_cn
0    Alice   Beijing     85      北京
1      Bob  Shanghai     92      上海
2  Charlie   Beijing     78      北京

In [27]:
s = pd.Series(['a', 'b', 'c'])
mapping_series = pd.Series(['A', 'B', 'C'], index=['a', 'b', 'c'])
result = s.map(mapping_series)
print(result)
# 输出:
# 0    A
# 1    B
# 2    C
# dtype: object

0    A
1    B
2    C
dtype: str

In [28]:
df = pd.DataFrame({
    'gender': ['M', 'F', 'Male', 'Female', 'm', 'f']
})

# 统一性别格式
gender_mapping = {
    'M': 'Male', 'm': 'Male', 'Male': 'Male',
    'F': 'Female', 'f': 'Female', 'Female': 'Female'
}
df['gender_clean'] = df['gender'].map(gender_mapping)
print(df)

   gender gender_clean
0       M         Male
1       F       Female
2    Male         Male
3  Female       Female
4       m         Male
5       f       Female

In [29]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data = data.replace(-999, np.nan, inplace=True)
data
# 输出:
# 0    1.0
# 1    NaN
# 2    2.0
# 3    NaN
# 4    -1000.0
# 5    3.0
# dtype: float64

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [30]:
data.replace([-999, -1000], np.nan, inplace=True)
# 这行代码的意思是把 data 中的 -999 和 -1000 都替换成 np.nan，inplace=True 表示直接在原 data 上修改，而不是返回一个新的 Series。

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [31]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [32]:
data = pd.DataFrame(
    np.arange(12).reshape((3, 4)),
    index=['Ohio', 'Colorado', 'New York'],
    columns=['one', 'two', 'three', 'four'],
    )
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [33]:
data.index = data.index.map(lambda x: x[:4].upper())
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [34]:
data.rename(index=str.title, columns=str.upper)
# index=str.title：对索引（行名）应用 str.title() 函数（首字母大写）
# columns=str.upper：对列名应用 str.upper() 函数（全部大写）

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [35]:
import pandas as pd

data = pd.DataFrame({
    'name': ['Alice', 'Bob'],
    'age': [25, 30],
    'city': ['Beijing', 'Shanghai']
}, index=['row_one', 'row_two'])

print("原始数据:")
print(data)
# 输出:
#           name  age      city
# row_one  Alice   25   Beijing
# row_two    Bob   30  Shanghai

# 修改索引和列名
result = data.rename(index=str.title, columns=str.upper)
print("\n修改后:")
print(result)
# 输出:
#           NAME  AGE      CITY
# Row_One  Alice   25   Beijing
# Row_Two    Bob   30  Shanghai

原始数据:
          name  age      city
row_one  Alice   25   Beijing
row_two    Bob   30  Shanghai

修改后:
          NAME  AGE      CITY
Row_One  Alice   25   Beijing
Row_Two    Bob   30  Shanghai

In [36]:
# 假设从 Excel 读取的数据列名不规范
data = pd.DataFrame({
    '  Name ': ['Alice', 'Bob'],
    'AGE': [25, 30],
    'city ': ['Beijing', 'Shanghai']
}, index=['001', '002'])

# 清理列名：去空格 + 转小写
data.columns = data.columns.str.strip().str.lower()

# 或者用 rename
data = data.rename(columns=lambda x: x.strip().lower())

print(data)
# 输出:
#       name  age      city
# 001  Alice   25   Beijing
# 002    Bob   30  Shanghai

      name  age      city
001  Alice   25   Beijing
002    Bob   30  Shanghai

In [ ]:
# ============================================
# 第一部分：导入必要的库
# ============================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 设置中文字体（Windows）
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False

# ============================================
# 第二部分：创建示例数据（实际项目中用 pd.read_csv 等读取）
# ============================================
np.random.seed(42)

# 生成 1000 条销售记录
n = 1000
data = pd.DataFrame({
    '订单编号': [f'ORD{str(i).zfill(5)}' for i in range(1, n+1)],
    '订单日期': pd.date_range('2023-01-01', periods=n, freq='D'),
    '客户ID': np.random.choice([f'C{str(i).zfill(3)}' for i in range(1, 101)], n),
    '产品类别': np.random.choice(['电子产品', '服装', '食品', '家居', '图书'], n, 
                                p=[0.3, 0.25, 0.2, 0.15, 0.1]),
    '产品名称': np.random.choice(['手机', '电脑', 'T恤', '裤子', '零食', '饮料', 
                                 '沙发', '台灯', '小说', '教材'], n),
    '数量': np.random.randint(1, 10, n),
    '单价': np.random.uniform(10, 5000, n).round(2),
    '城市': np.random.choice(['北京', '上海', '广州', '深圳', '杭州', '成都'], n),
    '客户评分': np.random.choice([1, 2, 3, 4, 5], n, p=[0.05, 0.1, 0.2, 0.35, 0.3]),
})

# 计算总金额
data['总金额'] = data['数量'] * data['单价']

# 人为添加一些脏数据（模拟真实场景）
data.loc[np.random.choice(n, 50), '数量'] = np.nan  # 50个缺失值
data.loc[np.random.choice(n, 30), '单价'] = np.nan  # 30个缺失值
data.loc[np.random.choice(n, 20), '城市'] = '未知'   # 20个异常值

print("原始数据形状:", data.shape)
print("\n前5行数据:")
print(data.head())

# ============================================
# 第三部分：数据清洗
# ============================================
print("\n" + "="*60)
print("数据清洗阶段")
print("="*60)

# 1. 查看数据基本信息
print("\n数据信息:")
print(data.info())

print("\n缺失值统计:")
print(data.isnull().sum())

print("\n数值型数据描述统计:")
print(data.describe())

# 2. 处理缺失值
# 数量用中位数填充
data['数量'] = data['数量'].fillna(data['数量'].median())

# 单价用中位数填充
data['单价'] = data['单价'].fillna(data['单价'].median())

# 重新计算总金额
data['总金额'] = data['数量'] * data['单价']

# 3. 处理异常值
# 删除"未知"城市的记录
data = data[data['城市'] != '未知']

# 4. 数据转换
# 提取月份
data['月份'] = data['订单日期'].dt.month
data['星期'] = data['订单日期'].dt.day_name()

# 价格区间分类
data['价格区间'] = pd.cut(data['单价'], 
                          bins=[0, 100, 500, 1000, 5000],
                          labels=['低价(0-100)', '中价(100-500)', '高价(500-1000)', '超高价(1000+)'])

print("\n清洗后数据形状:", data.shape)
print("\n清洗后缺失值统计:")
print(data.isnull().sum())

# ============================================
# 第四部分：探索性数据分析 (EDA)
# ============================================
print("\n" + "="*60)
print("探索性数据分析")
print("="*60)

# 1. 各产品类别销售情况
print("\n各产品类别销售统计:")
category_sales = data.groupby('产品类别').agg({
    '订单编号': 'count',
    '总金额': ['sum', 'mean'],
    '数量': 'sum'
}).round(2)
category_sales.columns = ['订单数', '总销售额', '平均订单金额', '总销量']
print(category_sales)

# 2. 各城市销售情况
print("\n各城市销售统计:")
city_sales = data.groupby('城市')['总金额'].sum().sort_values(ascending=False)
print(city_sales)

# 3. 月度销售趋势
print("\n月度销售趋势:")
monthly_sales = data.groupby('月份')['总金额'].sum()
print(monthly_sales)

# 4. 客户评分分布
print("\n客户评分分布:")
rating_dist = data['客户评分'].value_counts().sort_index()
print(rating_dist)

# 5. 高价值客户分析（消费前10）
print("\n消费Top 10客户:")
top_customers = data.groupby('客户ID')['总金额'].sum().sort_values(ascending=False).head(10)
print(top_customers)

# ============================================
# 第五部分：数据可视化
# ============================================
print("\n" + "="*60)
print("数据可视化")
print("="*60)

# 创建图表
fig, axes = plt.subplots(2, 3, figsize=(18, 12))
fig.suptitle('电商销售数据分析报告', fontsize=16, fontweight='bold')

# 图1：各产品类别销售额
ax1 = axes[0, 0]
category_total = data.groupby('产品类别')['总金额'].sum().sort_values(ascending=False)
category_total.plot(kind='bar', ax=ax1, color='skyblue')
ax1.set_title('各产品类别销售额')
ax1.set_ylabel('销售额（元）')
ax1.tick_params(axis='x', rotation=45)

# 图2：月度销售趋势
ax2 = axes[0, 1]
monthly_sales.plot(kind='line', ax=ax2, marker='o', color='red', linewidth=2)
ax2.set_title('月度销售趋势')
ax2.set_xlabel('月份')
ax2.set_ylabel('销售额（元）')
ax2.grid(True, alpha=0.3)

# 图3：各城市销售额
ax3 = axes[0, 2]
city_sales.plot(kind='barh', ax=ax3, color='lightgreen')
ax3.set_title('各城市销售额')
ax3.set_xlabel('销售额（元）')

# 图4：客户评分分布
ax4 = axes[1, 0]
rating_dist.plot(kind='pie', ax=ax4, autopct='%1.1f%%', colors=['#ff9999', '#66b3ff', '#99ff99', '#ffcc99', '#ff99cc'])
ax4.set_title('客户评分分布')

# 图5：价格区间分布
ax5 = axes[1, 1]
price_dist = data['价格区间'].value_counts()
price_dist.plot(kind='bar', ax=ax5, color='orange')
ax5.set_title('价格区间分布')
ax5.set_ylabel('订单数')
ax5.tick_params(axis='x', rotation=45)

# 图6：销售额与数量散点图
ax6 = axes[1, 2]
sample_data = data.sample(100)  # 抽样100条避免过于密集
ax6.scatter(sample_data['数量'], sample_data['总金额'], alpha=0.6, c='purple')
ax6.set_title('数量与总金额关系')
ax6.set_xlabel('数量')
ax6.set_ylabel('总金额（元）')

plt.tight_layout()
plt.show()

# ============================================
# 第六部分：深入分析
# ============================================
print("\n" + "="*60)
print("深入分析")
print("="*60)

# 1. 产品类别 × 城市 交叉分析
print("\n各城市各类别销售额:")
cross_tab = pd.pivot_table(data, 
                           values='总金额', 
                           index='城市', 
                           columns='产品类别', 
                           aggfunc='sum',
                           fill_value=0)
print(cross_tab.round(2))

# 2. 客户复购分析
customer_orders = data.groupby('客户ID')['订单编号'].nunique()
repeat_customers = customer_orders[customer_orders > 1]
print(f"\n复购客户数: {len(repeat_customers)}")
print(f"复购率: {len(repeat_customers) / customer_orders.nunique() * 100:.2f}%")

# 3. 高价值产品分析
print("\n销售额Top 10产品:")
top_products = data.groupby('产品名称')['总金额'].sum().sort_values(ascending=False).head(10)
print(top_products)

# ============================================
# 第七部分：得出结论和建议
# ============================================
print("\n" + "="*60)
print("分析结论与建议")
print("="*60)

best_category = category_total.idxmax()
best_city = city_sales.idxmax()
best_month = monthly_sales.idxmax()

print(f"""
📊 关键发现：

1. 最畅销产品类别：{best_category}（销售额：{category_total.max():.2f}元）
2. 最佳销售城市：{best_city}（销售额：{city_sales.max():.2f}元）
3. 销售高峰月份：第{best_month}月（销售额：{monthly_sales.max():.2f}元）
4. 平均客户评分：{data['客户评分'].mean():.2f}/5.0
5. 复购客户数：{len(repeat_customers)}人

💡 业务建议：

1. 加大{best_category}类的营销投入
2. 在{best_city}等表现好的城市扩大市场份额
3. 在第{best_month}月前提前备货，抓住销售旺季
4. 关注评分较低的产品，改进质量或服务
5. 设计会员制度，提高客户复购率
""")

# ============================================
# 第八部分：导出结果
# ============================================
# 保存清洗后的数据
# data.to_csv('cleaned_data.csv', index=False, encoding='utf-8-sig')

# 保存分析结果
# category_sales.to_csv('category_sales.csv', encoding='utf-8-sig')
# city_sales.to_csv('city_sales.csv', encoding='utf-8-sig')

print("✅ 分析完成！")

In [ ]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
print(age_categories.categories)
age_categories.codes # 每个元素所属的分类索引
age_categories.value_counts() # 每个分类的元素数量

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [ ]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [ ]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, str): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [ ]:
data = np.random.rand(20)
data = pd.cut(data, 4, precision=2) 
# 将 data 中的数据等分成 4 个区间（分箱），区间端点保留 2 位小数。
data.value_counts()

(0.0029, 0.24]    8
(0.24, 0.48]      4
(0.48, 0.72]      3
(0.72, 0.96]      5
Name: count, dtype: int64

In [ ]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4)
# 将 data 中的数据等分成 4 个区间（分箱），每个区间包含相同数量的元素。
cats.value_counts()

(-3.5829999999999997, -0.768]    250
(-0.768, -0.0577]                250
(-0.0577, 0.659]                 250
(0.659, 3.24]                    250
Name: count, dtype: int64

In [ ]:
cats = pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.], labels=['low', 'medium', 'high', 'very high'])
cats.value_counts()

low          100
medium       400
high         400
very high    100
Name: count, dtype: int64

In [ ]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.037611    -0.029406     0.020532     0.005189
std       0.995605     1.027272     0.993191     1.022502
min      -3.141415    -3.347551    -3.254479    -3.216057
25%      -0.696526    -0.697241    -0.639713    -0.703157
50%      -0.022248    -0.028468    -0.022533     0.012146
75%       0.647867     0.669335     0.697432     0.700246
max       3.149648     2.891659     3.276399     3.544065

In [ ]:
data[2][np.abs(data[2]) > 3]

51    -3.254479
271    3.276399
Name: 2, dtype: float64

In [ ]:
data[(np.abs(data) > 3).any(axis=1)]
# 找到所有绝对值大于 3 的行

            0         1         2         3
51  -0.903912 -1.798414 -3.254479  1.195453
153 -0.495492 -3.347551 -0.409423  0.230658
271 -0.619636 -0.881315  3.276399  0.540024
276 -0.770787  1.434408 -0.896666 -3.031194
295  0.491909 -1.073055 -0.421487 -3.216057
477 -3.116653  0.051992  1.304066 -1.047150
480 -0.150252 -0.040613  0.716331  3.398127
632  3.149648  1.105601 -0.104900  1.052202
646 -3.141415  0.793758  0.494040  1.352942
670  1.330157 -0.149134 -1.893994  3.544065
853 -3.017647 -0.717662  0.654024 -0.752905

In [ ]:
import pandas as pd
import numpy as np

# 示例数据
data = pd.DataFrame({
    'A': [1, 2, 4, -5],
    'B': [0.5, 3.5, 1, 2],
    'C': [1, 1, 1, 1]
})

# 步骤分解：
# 1. 计算绝对值
print(np.abs(data))
#    A    B    C
# 0  1  0.5  1.0
# 1  2  3.5  1.0
# 2  4  1.0  1.0
# 3  5  2.0  1.0

# 2. 判断是否大于 3
print(np.abs(data) > 3)
#        A      B      C
# 0  False  False  False
# 1  False   True  False
# 2   True  False  False
# 3   True  False  False

# 3. 按行判断是否有任何一个为 True
print((np.abs(data) > 3).any(axis=1))
# 0    False
# 1     True
# 2     True
# 3     True
# dtype: bool

# 4. 筛选行
result = data[(np.abs(data) > 3).any(axis=1)]
print(result)
#    A    B  C
# 1  2  3.5  1
# 2  4  1.0  1
# 3 -5  2.0  1

   A    B  C
0  1  0.5  1
1  2  3.5  1
2  4  1.0  1
3  5  2.0  1
       A      B      C
0  False  False  False
1  False   True  False
2   True  False  False
3   True  False  False
0    False
1     True
2     True
3     True
dtype: bool
   A    B  C
1  2  3.5  1
2  4  1.0  1
3 -5  2.0  1

In [ ]:
data = pd.DataFrame(np.random.randn(1000, 4), columns=['A', 'B', 'C', 'D'])
data[['A', 'B']]
data[1:4]
data.loc[1:4, 'A':'C'] # 包含 'C'

          A         B         C
1  1.767757 -1.011927 -0.796481
2  0.085816  0.043792  1.513241
3 -0.790767  0.873396 -1.243516
4  0.118460 -1.131886  1.064659

In [ ]:
# 假设索引是日期
dates = pd.date_range('2023-01-01', periods=5)
data = pd.DataFrame(np.random.randn(5, 2), 
                    index=dates, 
                    columns=['A', 'B'])

# .loc 按日期标签 - 包含结束日期
data.loc['2023-01-02':'2023-01-04']
# 包含 01-02, 01-03, 01-04 三天

# .iloc 按位置 - 不包含结束位置
data.iloc[1:4]
# 包含位置 1, 2, 3（第2、3、4行）

                   A         B
2023-01-02 -1.010086  0.161185
2023-01-03 -0.552905 -0.486406
2023-01-04  0.196991 -0.497591

In [ ]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4))) 
# reshape((5, 4))是将一维数组转换为二维数组
# np.arange(5 * 4)生成一个从 0 到 19 的 20 个整数的数组
sampler = np.random.permutation(5)
# permutation(5)生成一个从 0 到 4 的随机排列
# sampler 是一个随机的 5 个整数的数组，每个整数从 0 到 4 且不重复
df.iloc[sampler]
# sampler 中的索引是随机的，所以每次运行结果不同
# .iloc是属性，.take是方法

df.sample(n=3)
# 随机采样 3 行

df.sample(frac=1)  # frac=1 表示返回所有行，但随机排序

    0   1   2   3
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7
4  16  17  18  19

In [ ]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
# 从 choices 中随机采样 10 个元素，允许重复
draws

0    5
0    5
4    4
4    4
4    4
2   -1
3    6
1    7
1    7
1    7
dtype: int64

In [ ]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
pd.get_dummies(df['key'])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [ ]:
import pandas as pd

df = pd.DataFrame({
    '姓名': ['张三', '李四', '王五'],
    '城市': ['北京', '上海', '广州'],
    '工资': [8000, 12000, 15000]
})

print(df)
#    姓名  城市     工资
# 0  张三  北京   8000
# 1  李四  上海  12000
# 2  王五  广州  15000

# 对'城市'列进行独热编码
dummies = pd.get_dummies(df['城市'])
print(dummies)
#    北京  广州  上海
# 0   1   0   0
# 1   0   0   1
# 2   0   1   0

# 方法1：直接拼接
df_with_dummies = pd.concat([df, dummies], axis=1) # axis=1 表示按列拼接
print(df_with_dummies)
#    姓名  城市     工资  北京  广州  上海
# 0  张三  北京   8000   1   0   0
# 1  李四  上海  12000   0   0   1
# 2  王五  广州  15000   0   1   0

# 方法2：删除原列
df_final = pd.concat([df.drop('城市', axis=1), dummies], axis=1)
# df.drop('城市', axis=1)删除'城市'列,并返回一个新的DataFrame
print(df_final)
#    姓名     工资  北京  广州  上海
# 0  张三   8000   1   0   0
# 1  李四  12000   0   0   1
# 2  王五  15000   0   1   0

   姓名  城市     工资
0  张三  北京   8000
1  李四  上海  12000
2  王五  广州  15000
      上海     北京     广州
0  False   True  False
1   True  False  False
2  False  False   True
   姓名  城市     工资     上海     北京     广州
0  张三  北京   8000  False   True  False
1  李四  上海  12000   True  False  False
2  王五  广州  15000  False  False   True
   姓名     工资     上海     北京     广州
0  张三   8000  False   True  False
1  李四  12000   True  False  False
2  王五  15000  False  False   True

In [ ]:
df = pd.DataFrame({
    '城市': ['北京', '上海', '广州'],
    '性别': ['男', '女', '男']
})

# 对所有类别列进行编码
dummies = pd.get_dummies(df)
print(dummies)
#    城市_北京  城市_广州  城市_上海  性别_女  性别_男
# 0       1       0       0      0      1
# 1       0       0       1      1      0
# 2       0       1       0      0      1

   城市_上海  城市_北京  城市_广州   性别_女   性别_男
0  False   True  False  False   True
1   True  False  False   True  False
2  False  False   True  False   True

In [ ]:
dummies = pd.get_dummies(df['城市'], prefix='City')
# prefix='City' 表示为每个类别添加前缀'City_'
print(dummies)
#    City_北京  City_广州  City_上海
# 0         1         0         0
# 1         0         0         1
# 2         0         1         0

   City_上海  City_北京  City_广州
0    False     True    False
1     True    False    False
2    False    False     True

In [ ]:
df = pd.DataFrame({
    '颜色': ['红', '蓝', '绿', '红', '蓝'],
    '尺寸': ['S', 'M', 'L', 'M', 'S'],
    '价格': [100, 200, 300, 150, 250]
})

# 编码所有类别列
encoded = pd.get_dummies(df, columns=['颜色', '尺寸'], prefix=['Color', 'Size'])
print(encoded)
#    价格  Color_红  Color_蓝  Color_绿  Size_L  Size_M  Size_S
# 0   100       1       0       0       0       0       1
# 1   200       0       1       0       0       1       0
# 2   300       0       0       1       1       0       0
# 3   150       1       0       0       0       1       0
# 4   250       0       1       0       0       0       1

    价格  Color_红  Color_绿  Color_蓝  Size_L  Size_M  Size_S
0  100     True    False    False   False   False    True
1  200    False    False     True   False    True   False
2  300    False     True    False    True   False   False
3  150     True    False    False   False    True   False
4  250    False    False     True   False   False    True

In [ ]:
import pandas as pd

df = pd.DataFrame({
    '姓名': ['张三', '李四', '王五'],
    '城市': ['北京', '上海', '广州'],
    '工资': [8000, 12000, 15000]
})

print("原始数据:")
print(df)
#    姓名  城市     工资
# 0  张三  北京   8000
# 1  李四  上海  12000
# 2  王五  广州  15000

# 删除'城市'列
result = df.drop('城市', axis=1)
print("\n删除后:")
print(result)
#    姓名     工资
# 0  张三   8000
# 1  李四  12000
# 2  王五  15000

原始数据:
   姓名  城市     工资
0  张三  北京   8000
1  李四  上海  12000
2  王五  广州  15000

删除后:
   姓名     工资
0  张三   8000
1  李四  12000
2  王五  15000

In [ ]:
val = 'a,b,  guido'
pieces = [x.strip() for x in val.split(',')] # 移除每个元素的首尾空格
first, second, third = pieces
first+':'+second+third
'::'.join(pieces)
'guido' in val
val.index('b') # index of 'b' in val,返回位置
val.find(':')

-1

In [ ]:
val = "hello:world"

# 1. .index() - 找不到时抛出异常
val.index(':')    # 返回 5
# val.index('xyz')  ValueError: substring not found ❌

# 2. .find() - 找不到时返回 -1
val.find(':')     # 返回 5
val.find('xyz')   # 返回 -1 ✅

-1

In [ ]:
val = "Data Wrangling: Join,Combine, and Reshape"
val.lower().replace(',', '_')

'data wrangling: join_combine_ and reshape'

In [ ]:
import re

val = "Data Wrangling: Join,Combine, and Reshape    "

result= re.sub(r'[\s:,]+', '_', val.strip().lower()) + '.ipynb'
# re.sub(正则表达式, 替换成什么, 在哪个字符串中操作)
# r'...'  # 前面的 r 表示"原始字符串"，让 \ 不被转义`
# 方括号表示"匹配括号内的任意一个字符"
# \s 空白字符
# [\s:,] 匹配空格、冒号、逗号中的任意一个
# + 匹配一个或多个连续的字符

print(result)

data_wrangling_join_combine_and_reshape.ipynb

In [ ]:
import re

# 练习1：将多个空格合并成一个
re.sub(r' +', ' ', 'hello    world')
# 'hello world'

# 练习2：去除所有标点
re.sub(r'[,.!?]', '', 'hello, world! how are you?')
# 'hello world how are you'

# 练习3：提取数字
re.findall(r'\d+', 'phone: 138-0000-1234')
# ['138', '0000', '1234']

['138', '0000', '1234']

In [ ]:
text = "foo    bar\t baz  \tqux"
print(text)

re.sub(r'\s+', ' ', text)
re.split(r'\s+', text)
re.findall(r'\s+', text)

foo    bar	 baz  	qux

['    ', '\t ', '  \t']

In [ ]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

regex = re.compile(pattern, flags=re.IGNORECASE)
# 这行代码用于预编译正则表达式，并设置忽略大小写的标志

print(regex.findall(text))

m = regex.search(text)
print(m)
# search返回的是文本中第一个电子邮件地址（以特殊的匹配项对象形式返回）

for m in regex.finditer(text):
    print(m.group(), m.span())

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']
<re.Match object; span=(5, 20), match='dave@google.com'>
dave@google.com (5, 20)
steve@gmail.com (27, 42)
rob@gmail.com (47, 60)
ryan@yahoo.com (66, 80)

In [ ]:
import re

regex = re.compile(r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+\.[A-Z]{2,4})', re.IGNORECASE)
text = "邮箱: admin@company.com"

m = regex.search(text)
# search返回的是文本中第一个电子邮件地址（以特殊的匹配项对象形式返回）

if m:  # 先检查是否匹配成功
    print(f"完整匹配: {m.group()}")       # 'admin@company.com'
    print(f"用户名: {m.group(1)}")        # 'admin'
    print(f"域名: {m.group(2)}")          # 'company.com'
    print(f"位置: {m.span()}")            # (3, 20)
else:
    print("未找到匹配")

完整匹配: admin@company.com
用户名: admin
域名: company.com
位置: (4, 21)

In [ ]:
print('a','\n','b',sep='')
print(f'a\nb')

a
b
a
b

In [ ]:
data = pd.Series(np.random.randn(9),index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],[1, 2, 3, 1, 3, 1, 2, 2, 3]])
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
print('shuju' + '\n', end = '' )

shuju

In [ ]:
import re


def to_notebook_name(title):
    return re.sub(r'[\s:,]+', '_', title.strip().lower()) + '.ipynb'


val = "Data Wrangling: Join,Combine, and Reshape    "
result = to_notebook_name(val)
print(result)

data_wrangling_join_combine_and_reshape.ipynb